name = "AeronTensorPool"
uuid = "6ad55a46-f6a9-4b6f-a099-2d80be27a373"
version = "0.1.0"
authors = ["Darryl Gamroth <dgamroth@rubus.ca>"]

[deps]
Aeron = "b850ffb1-6704-484e-996b-4710e2f097f0"
Agent = "f7939a7f-2bcc-4096-952b-c44031b5533b"
Clocks = "6b5ade5d-6e95-4584-b343-73eec2e8782b"
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
FixedSizeArrays = "3821ddf9-e5b5-40d5-8e25-6813ab96b5e2"
Hsm = "ae4ab49b-60bf-4949-b8fd-fb49b1a0d067"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
LoggingFormats = "98105f81-4425-4516-93fd-1664fb551ab6"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
SBE = "b5db94cf-04c1-4db7-9b05-47f582871ea8"
SnowflakeId = "f9ebe2b0-2178-47c6-b9d1-20f9bee126a8"
StringViews = "354b36f9-a18e-4713-926e-db85100087ba"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
UnsafeArrays = "c4a57d5a-5b31-53a6-b365-19f8c011fbd6"

[compat]
Aeron = "0.18"
Agent = "0.3"
Aqua = "0.8"
Clocks = "0.2.1"
EnumX = "1.0.5"
FixedSizeArrays = "1.2.0"
Hsm = "0.1.5"
LoggingExtras = "1.2"
LoggingFormats = "1.5"
MappedArrays = "0.4.3"
Mmap = "1.11.0"
SBE = "0.2"
SnowflakeId = "0.1"
StringViews = "1.3.6"
TOML = "1.0.3"
UnsafeArrays = "1.0.8"
julia = "1.10"

[apps.tp_driver]
julia_flags = ["--threads=auto", "--optimize=2"]
submodule = "Apps.TpDriverApp"

[apps.tp_tool]
julia_flags = ["--threads=auto", "--optimize=2"]
submodule = "Apps.TpToolApp"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
BenchmarkTools = "6e4b80f9-93f8-5d43-9091-946f9d80d615"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
bench = ["BenchmarkTools"]
test = ["Test", "Aqua"]
