name = "AeronTensorPool"
uuid = "6ad55a46-f6a9-4b6f-a099-2d80be27a373"
version = "0.1.0"
authors = ["Darryl Gamroth <dgamroth@rubus.ca>"]

[deps]
Aeron = "b850ffb1-6704-484e-996b-4710e2f097f0"
Agent = "f7939a7f-2bcc-4096-952b-c44031b5533b"
Clocks = "6b5ade5d-6e95-4584-b343-73eec2e8782b"
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
SBE = "b5db94cf-04c1-4db7-9b05-47f582871ea8"
StringViews = "354b36f9-a18e-4713-926e-db85100087ba"

[compat]
Aeron = "0.18"
Agent = "0.3"
Clocks = "0.2.1"
EnumX = "1.0.5"
MappedArrays = "0.4.3"
SBE = "0.2"
StringViews = "1.3.6"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
