[driver]
instance_id = "driver-example"
aeron_dir = ""
control_channel = "aeron:ipc?term-length=16m"
control_stream_id = 15000
announce_channel = "aeron:ipc?term-length=16m"
announce_stream_id = 15001
qos_channel = "aeron:ipc?term-length=16m"
qos_stream_id = 15002

[shm]
base_dir = "/dev/shm"
require_hugepages = false
page_size_bytes = 4096
permissions_mode = "660"

[policies]
allow_dynamic_streams = false
default_profile = "camera"
announce_period_ms = 1000
lease_keepalive_interval_ms = 1000
lease_expiry_grace_intervals = 3

[profiles.camera]
header_nslots = 64
payload_pools = [
  { pool_id = 1, stride_bytes = 1048576 }
]

[streams.cam1]
stream_id = 1
profile = "camera"
